services:
  web:
    build:
      context: .
      dockerfile: docker/base/Dockerfile
    command: bin/rails server -b 0.0.0.0 -p 3000
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:postgres@database:5432/backend_development
      REDIS_URL: redis://redis:6379/0
    volumes:
      - .:/rails
      - bundle:/usr/local/bundle
      - node_modules:/rails/node_modules
    depends_on:
      - database
      - redis

  worker:
    build:
      context: .
      dockerfile: docker/base/Dockerfile
    command: ruby bin/jobs
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:postgres@database:5432/backend_development
      REDIS_URL: redis://redis:6379/0
    volumes:
      - .:/rails
      - bundle:/usr/local/bundle
      - node_modules:/rails/node_modules
    depends_on:
      - database
      - redis

  database:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend_development
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data

  virtual_host:
    image: caddy:2
    depends_on:
      - web
    ports:
      - "3000:80"
    volumes:
      - ./docker/environment/development/Caddyfile:/etc/caddy/Caddyfile:ro

volumes:
  postgres_data:
  redis_data:
  bundle:
  node_modules:
