services:
  web:
    build:
      context: .
      dockerfile: docker/base/Dockerfile
    command: bundle exec puma -C config/puma.rb
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: "1"
      RAILS_SERVE_STATIC_FILES: "1"
      BACKEND_DATABASE_PASSWORD: postgres
      DATABASE_URL: postgres://backend:postgres@database:5432/backend_production
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - database
      - redis

  worker:
    build:
      context: .
      dockerfile: docker/base/Dockerfile
    command: ruby bin/jobs
    environment:
      RAILS_ENV: production
      BACKEND_DATABASE_PASSWORD: postgres
      DATABASE_URL: postgres://backend:postgres@database:5432/backend_production
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - database
      - redis

  database:
    image: postgres:16
    environment:
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend_production
    volumes:
      - production_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - production_redis_data:/data

  virtual_host:
    image: caddy:2
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./docker/environment/production/Caddyfile:/etc/caddy/Caddyfile:ro

volumes:
  production_postgres_data:
  production_redis_data:
